# Generated by Django 3.2.18 on 2023-03-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='name', max_length=100)),
                ('apellido', models.CharField(help_text='apellid', max_length=100)),
                ('email', models.CharField(help_text='email', max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
